module "atlas_advanced_cluster" {
  source = "./modules/mongodb_cluster"

  project_name                            = terraform.workspace
  org_id                                  = var.org_id
  region                                  = var.region
  cluster_name                            = terraform.workspace
  instance_size                           = var.instance_size
  teams                                   = var.teams
  mongodb_major_version                   = var.mongodb_major_version
  mongodb_version_release_system          = var.mongodb_version_release_system
  cluster_type                            = var.cluster_type
  num_shards                              = var.num_shards
  num_nodes                               = var.num_nodes
  backup_enabled                          = var.backup_enabled
  pit_enabled                             = var.pit_enabled
  disk_size_gb                            = var.disk_size_gb
  auto_scaling_disk_gb_enabled            = var.auto_scaling_disk_gb_enabled
  auto_scaling_compute_enabled            = var.auto_scaling_compute_enabled
  auto_scaling_compute_scale_down_enabled = var.auto_scaling_compute_scale_down_enabled
  auto_scaling_compute_min_instance_size  = var.auto_scaling_compute_min_instance_size
  auto_scaling_compute_max_instance_size  = var.auto_scaling_compute_max_instance_size
  volume_type                             = var.volume_type
  disk_iops                               = var.disk_iops
  encryption_at_rest_enabled              = var.encryption_at_rest_enabled
  termination_protection_enabled          = var.termination_protection_enabled
  private_link_enabled                    = var.private_link_enabled
  aws_private_link_region                 = var.region
  private_link_vpc_name                   = var.private_link_vpc_name
  private_subnet_ids                      = var.private_subnet_ids
  ingress_rules                           = var.ingress_rules
}